version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo-prod
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat1234@
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - /data/mongo:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # 기본설정(비밀번호 없음, 데이터 영속화만)
    volumes:
      - /data/redis:/data

  springboot:
    build: .      # law-n-road 프로젝트 Dockerfile 경로
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://chat:chat1234@@mongo-prod:27017/chatdb
      SPRING_REDIS_HOST: redis
      # Redis는 비밀번호 없이 사용 (환경변수 필요 시 추가)
    depends_on:
      - mongo
      - redis
    restart: always
