name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- grant execute permission for Gradlew ---
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build Backend JAR
        run: ./gradlew clean bootJar -x test

      - name: Build Frontend (with Yarn)
        working-directory: frontend
        run: |
          # 1) Yarn 전역 설치
          npm install -g yarn

          # 2) npm 관련 파일 제거
          rm -rf node_modules package-lock.json || true

          # 3) optional deps 무시하고 설치
          yarn install --frozen-lockfile

          # 4) 빌드
          yarn build

      - name: Deploy Backend Artifact
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BACKEND_SSH_HOST }}
          username: ${{ secrets.BACKEND_SSH_USER }}
          key: ${{ secrets.BACKEND_SSH_PRIVATE_KEY }}
          port: 22
          source: "build/libs/*.jar"
          target: "/opt/law-n-road-release/"

      - name: Migrate DB & Restart Backend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.BACKEND_SSH_HOST }}
          username: ${{ secrets.BACKEND_SSH_USER }}
          key: ${{ secrets.BACKEND_SSH_PRIVATE_KEY }}
          script: |
            mysql -h "${{ secrets.DB_HOST }}" -P "${{ secrets.DB_PORT }}" \
                  -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD }}" \
                  "${{ secrets.DB_NAME }}" < /opt/law-n-road-release/db/migrations/init.sql
            sudo systemctl daemon-reload
            sudo systemctl restart law-n-road-backend.service

      - name: Deploy Frontend Artifact
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FRONT_SSH_HOST }}
          username: ${{ secrets.FRONT_SSH_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          port: 22
          source: "frontend/dist/"
          target: "/opt/law-n-road-release/frontend/"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.FRONT_SSH_HOST }}
          username: ${{ secrets.FRONT_SSH_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          script: sudo systemctl reload nginx

      - name: Notify Slack (도로의-판정단)
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ROAD }}
