name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build Backend JAR
        run: ./gradlew clean bootJar -x test

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install -g yarn
          rm -rf node_modules package-lock.json yarn.lock || true
          yarn install --frozen-lockfile
          yarn build

      # ────────────────────────────────────────────────
      # Backend 배포 (프록시: 프론트 서버를 경유)
      # ────────────────────────────────────────────────
      - name: Deploy & Restart Backend
        uses: appleboy/scp-action@v1
        with:
          # 실제 백엔드 private 호스트/IP
          host: ${{ secrets.BACKEND_SSH_HOST }}
          port: 22
          username: ${{ secrets.BACKEND_SSH_USER }}
          # 로컬(Runner)에 로드된 프론트 키를 에이전트 포워딩 대신 직접 사용하려면 key_path:
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/opt/law-n-road-release/"

          # ProxyJump 설정
          proxy_host: ${{ secrets.FRONT_SSH_HOST }}
          proxy_port: 22
          proxy_username: ${{ secrets.FRONT_SSH_USER }}
          proxy_key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}

      - name: Migrate DB & Restart Backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_SSH_HOST }}
          port: 22
          username: ${{ secrets.BACKEND_SSH_USER }}
          # 프론트 키(push-through) 또는 백엔드 전용 키를 여기에 지정
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.FRONT_SSH_HOST }}
          proxy_port: 22
          proxy_username: ${{ secrets.FRONT_SSH_USER }}
          proxy_key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          script: |
            mysql -h "${{ secrets.DB_HOST }}" -P "${{ secrets.DB_PORT }}" \
                  -u "${{ secrets.DB_USER }}" -p"${{ secrets.DB_PASSWORD }}" \
                  "${{ secrets.DB_NAME }}" < /opt/law-n-road-release/db/migrations/init.sql
            sudo systemctl daemon-reload
            sudo systemctl restart law-n-road-backend.service

      # ────────────────────────────────────────────────
      # Frontend 배포 (직접 접근 가능)
      # ────────────────────────────────────────────────
      - name: Deploy Frontend Artifact
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FRONT_SSH_HOST }}
          port: 22
          username: ${{ secrets.FRONT_SSH_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          source: "frontend/dist/"
          target: "/opt/law-n-road-release/frontend/"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.FRONT_SSH_HOST }}
          port: 22
          username: ${{ secrets.FRONT_SSH_USER }}
          key: ${{ secrets.FRONT_SSH_PRIVATE_KEY }}
          script: sudo systemctl reload nginx

      - name: Notify Slack (도로의-판정단)
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ROAD }}
